name: Setup Rust
description: Install Rust tooling with Cache and Build Dependencies

inputs:
  target:
    description: Rust target platforms
    required: false
    default: x86_64-unknown-linux-gnu
  toolchain:
    description: Rust toolchain version to install
    required: true
    default: 1.85.0
  cache:
    description: Use sscache
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Create .env file with NATS environment variables
      shell: bash
      run: |
        set_env_var() {
          echo "$1=${!1:-$2}" >> $GITHUB_ENV
          echo "$1=${!1:-$2}" >> .env
        }
        set_env_var "NATS_SYSTEM_USER" "sys"
        set_env_var "NATS_SYSTEM_PASS" "sys"
        set_env_var "NATS_ADMIN_USER" "admin"
        set_env_var "NATS_ADMIN_PASS" "admin"
        set_env_var "DATABASE_URL" "postgresql://postgres:postgres@127.0.0.1:5432/fuel_streams?sslmode=disable"

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        target: ${{ inputs.target }}
        components: clippy, rustfmt
