{
 "title": "Fuel Streams / Consumer Metrics",
 "tags": [
  "pedronauck-streams",
  "consumer"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Consumer: Average duration [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(consumer_metrics_duration_milliseconds_sum[5m]) / rate(consumer_metrics_duration_milliseconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer: Maximum duration [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max by (action_type) (\n  histogram_quantile(1.0, rate(consumer_metrics_duration_milliseconds_bucket[1m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer: Average Packets Processed [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(consumer_metrics_packets_sum[5m]) / rate(consumer_metrics_packets_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer: Minimum duration [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "min by (action_type) (\n  consumer_metrics_duration_milliseconds_bucket{le!=\"0\"} > 0\n) * 1",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}