{
 "title": "Fuel Streams / Publisher Metrics",
 "tags": [
  "pedronauck-streams",
  "publisher"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Publisher: Total published messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(publisher_metrics_messages_throughput)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher: Average message size [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(publisher_metrics_message_size_bytes_sum[5m]) / rate(publisher_metrics_message_size_bytes_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher: Total failed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(publisher_metrics_error_rates)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher: Error rates by subject",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(publisher_metrics_error_rates[5m])) by (subject)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}