name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

env:
  RUST_VERSION: 1.84.0
  RUST_NIGHTLY_VERSION: nightly-2025-01-24

jobs:
  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ env.RUST_NIGHTLY_VERSION }}
          target: x86_64-unknown-linux-gnu,wasm32-unknown-unknown

      - name: Install nextest
        run: cargo install release-plz --locked

      - name: Run release-plz
        run: release-plz release \
          --token ${{ secrets.GITHUB_TOKEN }} \
          --backend github \
          --dry-run
